trigger:
- '*'

stages:
- stage: 'Provision'
  displayName: 'Provision Azure Kubernetes Service'
  dependsOn: Build
  jobs:
  - job: Provision
    displayName: 'Provision Azure Kubernetes Service'
    pool:
      vmImage: 'ubuntu-16.04'
    variables:
    - group: Release
    steps:
    - script: |
        # Exit when any command returns a failure status.
        set -e
 
        # Initialize Terraform.
        cd $(Build.SourcesDirectory)/terraform_k8s && terraform init -input=false -backend-config="backend.tfvars"
        # Apply the Terraform plan.
        terraform apply -input=false -auto-approve
  
      name: 'RunTerraform'
      displayName: 'Run Terraform'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        TF_VAR_client_id:  $(ARM_CLIENT_ID)
        TF_VAR_client_secret: $(ARM_CLIENT_SECRET)
